### ISSUE TITLE
Use a different data structure other than array for more reliability

### ISSUE THREAD

**Issue by jerryjohnjacob** [JAYKRISHNAN/calculator_using_javascript#1]
Check out lines https://github.com/JAYKRISHNAN/calculator_using_javascript/blob/master/src/calculator.js#L24-L26. They rely on the absolute position of elements in an array to work. You can switch to something more robust which does not depend on something like position of an element in an array.

**Comment by JAYKRISHNAN** [comment]
used hash instead

**Comment by jerryjohnjacob** [comment]
Let's use the correct technical term - object literal (not hash)
